Repository EinStack/glide, pull requests merged in 2024-06, with the labels that each got.

#267 #266: removing omitempty from response definition
  pkg/api/schemas/chat.go
Labels: api:http, model:language, type:refactoring

#271 🔧 #262: adding connection pool for chat request and response
  pkg/api/http/handlers.go
  pkg/api/schemas/pool.go
Labels: type:enhancement

#276 🔒 Updated golang to 1.22.4 to address CVE-2024-24790
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  .github/workflows/vuln.yaml
  .go-version
  go.mod
  images/alpine.Dockerfile
  images/distroless.Dockerfile
  images/redhat.Dockerfile
  images/ubuntu.Dockerfile
Labels: area:chores, area:build, type:security

#270 🔧 Adds support for Air live reloading
  .air.toml
  Makefile
Labels: type:enhancement

#277 🔧 #240: Automatically install air
  Makefile
Labels: type:enhancement
